### ISSUE TITLE
wasabi command is not found

### ISSUE THREAD

**Issue by Xinzhao1990** [MetaSUB/metasub_utils#3]
* MetaSUB Utilities version: 0.4.0
* Python version:3.6.0
* Operating System:macOS 10.14.1

### Description

Wasabi command is not working anymore after being updated to new version (v0.4.0)

### What I Did

```
Paste the command(s) you ran and the output.

XinzhaodeMacBook-Pro:~ Xinzhao$ metasub wasabi download-raw-reads --help
Unable to import metasub_utils.athena.cli
Unable to import metasub_utils.bridges.cli
Unable to import metasub_utils.hudson_alpha.cli
Unable to import metasub_utils.metadata.cli
Unable to import metasub_utils.metagenscope.cli
Unable to import metasub_utils.wasabi.cli
Usage: metasub [OPTIONS] COMMAND [ARGS]...
Try "metasub --help" for help.

Error: No such command "wasabi".
```

**Comment by dcdanko** [comment]
This is an issue with packaging microlibs that is fixed in PR #4 and v0.4.1 of the package.

Installation from pypi should work now, it did on my system. In case it does not work I would recommend installing from source until the bug is fixed.

When installing now pin the version explicitly `pip install metasub_utils==0.4.1` as pip may otherwise install a slightly stale version.
